package com.leo.remote.rfid.sdk.model;

public enum ConnectionPhase {
    DISCONNECTED,
    SCANNING,
    CONNECTING,
    DISCOVERING_SERVICES,
    ENABLING_NOTIFICATIONS,
    CONNECTING_DATA_CHANNEL,
    VERIFYING_MODULE,
    UPDATING_PARAMETERS,
    CONNECTED,
    DISCONNECTING,
    FAILED
}
